(()=>{
const CFG=window.WGH_CONFIG||{},DATA=Array.isArray(window.EVENTS)?window.EVENTS:[],Q=window.WGH_EVENT_QUALITY||{},H=window.WGH_EVENT_HEALTH||{},U=window.WGH_EVENT_UTILS||{},NS=CFG.analyticsNamespace||'wasgehtheute.ch';
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zurich'}).format(new Date()),future=DATA.filter(e=>e.end>=today),read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ymd(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function weekend(){const d=new Date(today+'T12:00:00'),dow=d.getDay();let add=(5-dow+7)%7;if(dow===6)add=-1;if(dow===0)add=-2;const f=new Date(d);f.setDate(d.getDate()+add);const s=new Date(f);s.setDate(f.getDate()+2);return[ymd(f),ymd(s)]}
function pct(n,d){return d?Math.round(n/d*100):0}
function stale(e){const c=U.checkedAt?.(e)||e.checked_at||e.verified_at;if(!/^\d{4}-\d{2}-\d{2}$/.test(String(c||'')))return true;return (new Date(today+'T12:00:00')-new Date(c+'T12:00:00'))/86400000>30}
const [fri,sun]=weekend(),todayEvents=future.filter(e=>e.start<=today&&e.end>=today),weekendEvents=future.filter(e=>e.start<=sun&&e.end>=fri),noVenue=future.filter(e=>!e.venue),noTicket=future.filter(e=>!e.ticket),oldCheck=future.filter(stale),cancelled=DATA.filter(e=>e.status==='cancelled'||e.quality_status==='cancelled-warning'),sourceIssues=future.filter(e=>!e.source||e.quality_status==='source-warning'),dupes=[...(Q.fuzzyDuplicates||[]),...(H.duplicates||[])];
const completeness=future.map(e=>[e.title,e.city,e.region,e.start,e.end,e.time,e.venue,e.source,e.desc,(e.cats||[]).length].filter(Boolean).length/10),qualityScore=future.length?Math.round(completeness.reduce((a,b)=>a+b,0)/future.length*100):0;
set('aEvents',future.length);set('aToday',todayEvents.length);set('aWeekend',weekendEvents.length);set('aQuality',qualityScore+' %');set('aNoVenue',noVenue.length);set('aNoTicket',noTicket.length);set('aOldCheck',oldCheck.length);set('aDuplicates',dupes.length);set('aSourceIssues',sourceIssues.length);set('aCancelled',cancelled.length);set('aDrafts',read('wgh_organizer_drafts_v1').length);
async function counter(){try{const r=await fetch(`https://counterapi.com/api/${encodeURIComponent(NS)}/pageview-total/all?readOnly=true`,{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();return Number(d.value)}catch{return null}}counter().then(n=>set('aViews',Number.isFinite(n)?n.toLocaleString('de-CH'):'nicht verfügbar'));
const metrics=[['Events vollständig',`${qualityScore} %`],['mit Quelle',`${pct(future.filter(e=>e.source).length,future.length)} %`],['mit offizieller/direkter Quelle',`${pct(future.filter(e=>(U.sourceRank?.(e)||0)>=3).length,future.length)} %`],['mit Venue',`${pct(future.filter(e=>e.venue).length,future.length)} %`],['mit Ticketlink',`${pct(future.filter(e=>e.ticket).length,future.length)} %`],['mit Preis/Gratis-Angabe',`${pct(future.filter(e=>e.price||(e.cats||[]).includes('Gratis')).length,future.length)} %`],['mit aktueller Prüfung ≤ 30 Tage',`${pct(future.length-oldCheck.length,future.length)} %`]];
const qm=document.getElementById('qualityMetrics');if(qm)qm.innerHTML=metrics.map(([a,b])=>`<div class="rank-row"><div><b>${esc(a)}</b></div><strong>${esc(b)}</strong></div>`).join('');
let issues=[];(H.issues||[]).forEach(x=>issues.push({title:x.title||x.id||'Event',note:x.reason||x.type||'Datenproblem'}));noVenue.slice(0,5).forEach(e=>issues.push({title:e.title,note:'Venue fehlt'}));sourceIssues.slice(0,5).forEach(e=>issues.push({title:e.title,note:!e.source?'Quelle fehlt':'Quelle problematisch'}));oldCheck.slice(0,5).forEach(e=>issues.push({title:e.title,note:'Prüfdatum fehlt oder ist älter als 30 Tage'}));dupes.slice(0,5).forEach(x=>issues.push({title:x.city||x.id||'Mögliche Dublette',note:'Ähnlicher Event am selben Datum erkannt'}));const qi=document.getElementById('qualityIssues');if(qi)qi.innerHTML=issues.length?issues.slice(0,15).map(x=>`<div class="rank-row"><div><b>${esc(x.title)}</b><br><small>${esc(x.note)}</small></div><strong>prüfen</strong></div>`).join(''):'<div class="rank-row"><div><b>Keine akuten Datenprobleme erkannt</b></div><strong>✓</strong></div>';
const status=[['Event-Datenquelle','zentraler Bestand'],['Tägliche Quellenprüfung',H.checked_at?`zuletzt ${H.checked_at}`:'wartet auf Lauf'],['Formularversand',CFG.organizerEndpoint||CFG.formEndpoint?'verbunden':'noch ohne Backend'],['Login/Auth',CFG.authEndpoint?'verbunden':'nicht eingerichtet'],['Eigene Domain',CFG.customDomain||'GitHub Pages']];const system=document.getElementById('systemStatus');if(system)system.innerHTML=status.map(([a,b])=>`<div class="rank-row"><div><b>${esc(a)}</b></div><strong>${esc(b)}</strong></div>`).join('');set('formState',CFG.organizerEndpoint||CFG.formEndpoint?'bereit':'Backend fehlt');set('authState',CFG.authEndpoint?'bereit':'offen');set('domainState',CFG.customDomain||'offen');
const drafts=read('wgh_organizer_drafts_v1'),adminDrafts=document.getElementById('adminDrafts');if(adminDrafts)adminDrafts.innerHTML=drafts.length?drafts.map(x=>`<div class="rank-row"><div><b>${esc(x.title||'Ohne Titel')}</b><br><small>${esc(x.date||'Kein Datum')} · ${esc(x.place||'Kein Ort')} · ${esc(x.org||'Unbekannt')}</small></div><strong>${esc(x.status||'Wartet auf Prüfung')}</strong></div>`).join(''):'<p>Auf diesem Gerät sind keine Einreichungen gespeichert.</p>';
})();
