const DATA=window.EVENTS||[];
const CFG=window.WGH_CONFIG||{},NS=CFG.analyticsNamespace||'wasgehtheute.ch',favKey='wgh_favorites_v1';
function slugify(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function eid(e){return slugify(e.title+'-'+e.city+'-'+e.start)}
function venue(e){return e.venue||e.location||e.city}
function price(e){if(e.price)return e.price;if((e.cats||[]).includes('Gratis'))return 'Gratis';return ''}
async function counter(name,up=false){try{const suffix=up?'':'?readOnly=true';const r=await fetch(`https://counterapi.com/api/${encodeURIComponent(NS)}/metric/${encodeURIComponent(name)}${suffix}`,{cache:'no-store'});if(!r.ok)throw new Error('counter');const d=await r.json();return Number(d.value??0)||0}catch{return 0}}
function getFavs(){try{const v=JSON.parse(localStorage.getItem(favKey)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function setFavs(v){try{localStorage.setItem(favKey,JSON.stringify([...new Set(v)]))}catch{}}
function calendarText(e){const esc=x=>String(x||'').replace(/[\\;,]/g,m=>'\\'+m).replace(/\n/g,'\\n');const start=String(e.start||'').replaceAll('-','');const d=new Date(`${e.end}T12:00:00`);d.setDate(d.getDate()+1);const end=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//WasGehtHeute.ch//DE\r\nBEGIN:VEVENT\r\nUID:${eid(e)}@wasgehtheute.ch\r\nDTSTART;VALUE=DATE:${start}\r\nDTEND;VALUE=DATE:${end}\r\nSUMMARY:${esc(e.title)}\r\nLOCATION:${esc(venue(e))}\r\nDESCRIPTION:${esc(e.desc)}\\n${esc(e.source)}\r\nURL:${e.source}\r\nEND:VEVENT\r\nEND:VCALENDAR`}
function downloadCalendar(e){const b=new Blob([calendarText(e)],{type:'text/calendar;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${slugify(e.title)||'event'}.ics`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
const id=new URLSearchParams(location.search).get('id')||'',event=DATA.find(e=>eid(e)===id),root=document.getElementById('eventDetail');
if(!root)throw new Error('eventDetail fehlt');
if(!event){document.title='Event nicht gefunden – WasGehtHeute.ch';root.innerHTML='<div class="detail-card"><div class="detail-content"><h1>Event nicht gefunden</h1><p class="detail-desc">Dieser Event ist möglicherweise abgelaufen oder wurde aktualisiert.</p><a class="cta-btn" href="index.html">Alle Events anzeigen</a></div></div>'}else{
 counter('event-'+id,true);counter('city-'+slugify(event.city),true);(event.cats||[]).slice(0,2).forEach(c=>counter('cat-'+slugify(c),true));
 document.title=`${event.title} – ${event.city} | WasGehtHeute.ch`;
 const desc=document.createElement('meta');desc.name='description';desc.content=`${event.title} in ${event.city}: ${event.date}, ${event.time}. ${event.desc}`;document.head.appendChild(desc);
 const canonical=document.createElement('link');canonical.rel='canonical';canonical.href=location.href.split('#')[0];document.head.appendChild(canonical);
 if(event.image){const og=document.createElement('meta');og.setAttribute('property','og:image');og.content=event.image;document.head.appendChild(og)}
 const isFav=getFavs().includes(id),p=price(event),v=venue(event),heroStyle=event.image?`style="background-image:linear-gradient(rgba(8,8,12,.25),rgba(8,8,12,.5)),url('${String(event.image).replace(/'/g,'')}');background-size:cover;background-position:center"`:'';
 root.innerHTML=`<article class="detail-card"><div class="detail-hero" ${heroStyle}><span class="date-badge">${event.date}</span><span class="place-badge">📍 ${event.city}</span>${event.image?'':`<span class="emoji">${event.emoji}</span>`}</div><div class="detail-content"><div class="verify-line"><span class="verified">✓ Quelle geprüft</span><span class="source-type">${event.source_type||'Geprüfte Quelle'}</span></div><div class="catline">${event.region} · ${(event.cats||[]).join(' · ')}</div><h1>${event.title}</h1><div class="detail-meta"><span>📅 ${event.date}</span><span>🕒 ${event.time}</span><span>📍 ${v}</span>${p?`<span>💳 ${p}</span>`:''}<span id="eventClicks">👀 … Klicks</span></div><p class="detail-desc">${event.desc}</p><div class="detail-actions"><a class="cta-btn" href="${event.source}" target="_blank" rel="noopener noreferrer">Offizielle Infos ↗</a>${event.ticket?`<a class="cta-btn" href="${event.ticket}" target="_blank" rel="noopener noreferrer" id="ticketEvent">🎟️ Tickets ↗</a>`:''}<button type="button" class="cta-btn secondary" id="shareEvent">📤 Teilen</button><button type="button" class="cta-btn secondary" id="calendarEvent">📅 Kalender</button><button type="button" class="cta-btn secondary" id="favoriteEvent" aria-pressed="${isFav}">${isFav?'❤️ Gespeichert':'🤍 Favorit'}</button></div><p class="detail-note">Termine, Preise und Verfügbarkeit können sich kurzfristig ändern. Massgebend ist die verlinkte Originalquelle.</p></div></article>`;
 const jsonLd={"@context":"https://schema.org","@type":"Event","name":event.title,"startDate":event.start,"endDate":event.end,"description":event.desc,"eventStatus":"https://schema.org/EventScheduled","eventAttendanceMode":"https://schema.org/OfflineEventAttendanceMode","location":{"@type":"Place","name":v,"address":{"@type":"PostalAddress","addressLocality":event.city,"addressCountry":"CH"}},"url":location.href.split('#')[0],"sameAs":event.source};if(event.image)jsonLd.image=[event.image];if(event.ticket)jsonLd.offers={"@type":"Offer","url":event.ticket,"availability":"https://schema.org/InStock",...(p&&p!=='Gratis'?{"price":String(p).replace(/[^0-9.,]/g,''),"priceCurrency":"CHF"}:{})};
 const script=document.createElement('script');script.type='application/ld+json';script.textContent=JSON.stringify(jsonLd);document.head.appendChild(script);
 counter('event-'+id,false).then(n=>{const el=document.getElementById('eventClicks');if(el)el.textContent=`👀 ${n} Klick${n===1?'':'s'}`});
 document.getElementById('shareEvent')?.addEventListener('click',async()=>{const share={title:event.title,text:`${event.title} – ${event.date} in ${event.city}`,url:location.href};if(navigator.share){try{await navigator.share(share);return}catch(err){if(err?.name==='AbortError')return}}try{await navigator.clipboard.writeText(location.href);alert('Link kopiert ✅')}catch{prompt('Link kopieren:',location.href)}});
 document.getElementById('calendarEvent')?.addEventListener('click',()=>downloadCalendar(event));
 document.getElementById('ticketEvent')?.addEventListener('click',()=>counter('ticket-'+id,true));
 document.getElementById('favoriteEvent')?.addEventListener('click',()=>{let f=getFavs();f=f.includes(id)?f.filter(x=>x!==id):[...f,id];setFavs(f);const saved=f.includes(id),btn=document.getElementById('favoriteEvent');if(btn){btn.textContent=saved?'❤️ Gespeichert':'🤍 Favorit';btn.setAttribute('aria-pressed',String(saved))}})
}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});