(()=>{
const DATA=Array.isArray(window.EVENTS)?window.EVENTS:[];
const U=window.WGH_EVENT_UTILS||{};
const CFG=window.WGH_CONFIG||{},NS=CFG.analyticsNamespace||'wasgehtheute.ch',favKey='wgh_favorites_v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>U.slug?U.slug(s):String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const eid=e=>U.id?U.id(e):slug(`${e?.title||''}-${e?.city||''}-${e?.start||''}`);
const venue=e=>e?.venue||e?.location||e?.city||'';
const price=e=>e?.price||((e?.cats||[]).includes('Gratis')?'Gratis':'');
const checked=e=>U.checkedAt?.(e)||e?.checked_at||e?.health_checked_at||e?.verified_at||'';
const deDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(String(s||''))?String(s).split('-').reverse().join('.'):String(s||'');
async function counter(name,up=false){try{const suffix=up?'':'?readOnly=true';const r=await fetch(`https://counterapi.com/api/${encodeURIComponent(NS)}/metric/${encodeURIComponent(name)}${suffix}`,{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();return Number(d.value??0)||0}catch{return null}}
function getFavs(){try{const v=JSON.parse(localStorage.getItem(favKey)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function setFavs(v){try{localStorage.setItem(favKey,JSON.stringify([...new Set(v)]))}catch{}}
function calendarText(e){const clean=x=>String(x||'').replace(/[\\;,]/g,m=>'\\'+m).replace(/\n/g,'\\n');const start=String(e.start||'').replaceAll('-','');const d=new Date(`${e.end||e.start}T12:00:00`);d.setDate(d.getDate()+1);const end=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//WasGehtHeute.ch//DE\r\nBEGIN:VEVENT\r\nUID:${eid(e)}@wasgehtheute.ch\r\nDTSTART;VALUE=DATE:${start}\r\nDTEND;VALUE=DATE:${end}\r\nSUMMARY:${clean(e.title)}\r\nLOCATION:${clean(venue(e))}\r\nDESCRIPTION:${clean(e.desc)}\\n${clean(e.source)}\r\nURL:${e.source||location.href}\r\nEND:VEVENT\r\nEND:VCALENDAR`}
function downloadCalendar(e){const blob=new Blob([calendarText(e)],{type:'text/calendar;charset=utf-8'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`${slug(e.title)||'event'}.ics`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function statusInfo(e){const code=e.status||'confirmed';const map={confirmed:['Bestätigt','confirmed'],postponed:['Verschoben','changed'],changed:['Termin geändert','changed'],'sold-out':['Ausverkauft','sold-out'],cancelled:['Abgesagt','cancelled']};const row=map[code]||[e.status_label||code,'changed'];return{code,label:e.status_label||row[0],cls:row[1]}}
function schemaStatus(code){if(code==='cancelled')return'https://schema.org/EventCancelled';if(code==='postponed')return'https://schema.org/EventPostponed';if(code==='changed')return'https://schema.org/EventRescheduled';return'https://schema.org/EventScheduled'}
const id=new URLSearchParams(location.search).get('id')||'',event=DATA.find(e=>eid(e)===id),root=document.getElementById('eventDetail');
if(!root)return;
if(!event){document.title='Event nicht gefunden – WasGehtHeute.ch';root.innerHTML='<div class="detail-card"><div class="detail-content"><h1>Event nicht gefunden</h1><p class="detail-desc">Dieser Event ist möglicherweise abgelaufen, wurde zusammengeführt oder aktualisiert.</p><a class="cta-btn" href="index.html">Alle Events anzeigen</a></div></div>';return}
const status=statusInfo(event),v=venue(event),p=price(event),last=checked(event),isFav=getFavs().includes(id),routeQuery=[v,event.city].filter(Boolean).join(', '),route=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(routeQuery)}`;
if(status.code!=='cancelled'){counter('event-'+id,true);counter('city-'+slug(event.city),true);(event.cats||[]).slice(0,2).forEach(c=>counter('cat-'+slug(c),true))}
document.title=`${event.title} – ${event.city} | WasGehtHeute.ch`;
const desc=document.createElement('meta');desc.name='description';desc.content=`${event.title} in ${event.city}: ${event.date||event.start}${event.time?', '+event.time:''}. ${event.desc||''}`.slice(0,250);document.head.appendChild(desc);
let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=location.href.split('#')[0];
if(event.image){const og=document.createElement('meta');og.setAttribute('property','og:image');og.content=event.image;document.head.appendChild(og)}
const heroStyle=event.image?`style="background-image:linear-gradient(rgba(8,8,12,.25),rgba(8,8,12,.62)),url('${esc(String(event.image).replace(/'/g,''))}');background-size:cover;background-position:center"`:'';
const statusHtml=status.code==='confirmed'?'':`<span class="status-badge ${esc(status.cls)}">${status.code==='cancelled'?'⛔':status.code==='sold-out'?'⚠️':'↪️'} ${esc(status.label)}</span>`;
root.innerHTML=`<article class="detail-card"><div class="detail-hero" ${heroStyle}><span class="date-badge">${esc(event.date||event.start)}</span><span class="place-badge">📍 ${esc(event.city)}</span>${event.image?'':`<span class="emoji">${esc(event.emoji||'📅')}</span>`}</div><div class="detail-content"><div class="verify-line"><span class="verified">✓ Quelle geprüft${last?' · '+esc(deDate(last)):''}</span><span class="source-type">${esc(event.source_type||'Geprüfte Quelle')}</span>${statusHtml}</div><div class="catline">${esc(event.region||'Schweiz')} · ${esc((event.cats||[]).join(' · '))}</div><h1>${esc(event.title)}</h1><div class="detail-meta"><span>📅 ${esc(event.date||event.start)}</span><span>🕒 ${esc(event.time||'Zeit siehe Quelle')}</span><span>📍 ${esc(v)}</span>${p?`<span>💳 ${esc(p)}</span>`:''}<span id="eventClicks">👀 … Klicks</span></div>${status.code==='cancelled'?'<div class="status-warning"><b>Dieser Event ist als abgesagt markiert.</b> Bitte prüfe die Originalquelle.</div>':''}${['postponed','changed'].includes(status.code)?`<div class="status-warning"><b>${esc(status.label)}.</b> Bitte beachte die Angaben der Originalquelle.</div>`:''}<p class="detail-desc">${esc(event.desc||'Weitere Informationen findest du bei der Originalquelle.')}</p><div class="detail-actions">${event.ticket&&status.code!=='cancelled'?`<a class="cta-btn" href="${esc(event.ticket)}" target="_blank" rel="noopener noreferrer" id="ticketEvent">🎟 Tickets</a>`:''}<a class="cta-btn secondary" href="${esc(route)}" target="_blank" rel="noopener noreferrer">🗺 Route öffnen</a><button type="button" class="cta-btn secondary" id="calendarEvent">📅 Zum Kalender</button><button type="button" class="cta-btn secondary" id="shareEvent">📤 Teilen</button><button type="button" class="cta-btn secondary" id="favoriteEvent" aria-pressed="${isFav}">${isFav?'❤️ Gespeichert':'🤍 Speichern'}</button>${event.source?`<a class="cta-btn secondary" href="${esc(event.source)}" target="_blank" rel="noopener noreferrer">✓ Originalquelle ↗</a>`:''}</div><p class="detail-note"><b>Status:</b> ${esc(status.label)}${last?` · <b>Zuletzt geprüft:</b> ${esc(deDate(last))}`:''}<br>Termine, Preise und Verfügbarkeit können sich kurzfristig ändern. Massgebend ist die verlinkte Originalquelle.</p></div></article>`;
const jsonLd={"@context":"https://schema.org","@type":"Event","name":event.title,"startDate":event.start,"endDate":event.end,"description":event.desc||'',"eventStatus":schemaStatus(status.code),"eventAttendanceMode":"https://schema.org/OfflineEventAttendanceMode","location":{"@type":"Place","name":v,"address":{"@type":"PostalAddress","addressLocality":event.city,"addressCountry":"CH"}},"url":location.href.split('#')[0]};if(event.source)jsonLd.sameAs=event.source;if(event.image)jsonLd.image=[event.image];if(event.ticket){jsonLd.offers={"@type":"Offer","url":event.ticket,"availability":status.code==='sold-out'?'https://schema.org/SoldOut':'https://schema.org/InStock',...(p&&p!=='Gratis'?{"price":String(p).replace(/[^0-9.,]/g,''),"priceCurrency":"CHF"}:p==='Gratis'?{"price":"0","priceCurrency":"CHF"}:{})}}const script=document.createElement('script');script.type='application/ld+json';script.textContent=JSON.stringify(jsonLd);document.head.appendChild(script);
counter('event-'+id,false).then(n=>{const el=document.getElementById('eventClicks');if(el)el.textContent=n===null?'👀 Statistik nicht verfügbar':`👀 ${n.toLocaleString('de-CH')} Klick${n===1?'':'s'}`});
document.getElementById('shareEvent')?.addEventListener('click',async()=>{const share={title:event.title,text:`${event.title} – ${event.date||event.start} in ${event.city}`,url:location.href};if(navigator.share){try{await navigator.share(share);return}catch(err){if(err?.name==='AbortError')return}}try{await navigator.clipboard.writeText(location.href);alert('Link kopiert ✅')}catch{prompt('Link kopieren:',location.href)}});
document.getElementById('calendarEvent')?.addEventListener('click',()=>downloadCalendar(event));
document.getElementById('ticketEvent')?.addEventListener('click',()=>counter('ticket-'+id,true));
document.getElementById('favoriteEvent')?.addEventListener('click',()=>{let favs=getFavs();favs=favs.includes(id)?favs.filter(x=>x!==id):[...favs,id];setFavs(favs);const saved=favs.includes(id),btn=document.getElementById('favoriteEvent');if(btn){btn.textContent=saved?'❤️ Gespeichert':'🤍 Speichern';btn.setAttribute('aria-pressed',String(saved))}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
