const DATA=window.EVENTS||[];
function slugify(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
const id=new URLSearchParams(location.search).get('id')||'';
const event=DATA.find(e=>slugify(e.title+'-'+e.city+'-'+e.start)===id);
const root=document.getElementById('eventDetail');
if(!event){document.title='Event nicht gefunden – WasGehtHeute.ch';root.innerHTML='<div class="detail-card"><div class="detail-content"><h1>Event nicht gefunden</h1><p class="detail-desc">Dieser Event ist möglicherweise abgelaufen oder wurde aktualisiert.</p><a class="cta-btn" href="index.html">Alle Events anzeigen</a></div></div>';}else{
  document.title=`${event.title} – ${event.city} | WasGehtHeute.ch`;
  const desc=document.createElement('meta');desc.name='description';desc.content=`${event.title} in ${event.city}: ${event.date}, ${event.time}. ${event.desc}`;document.head.appendChild(desc);
  const canonical=document.createElement('link');canonical.rel='canonical';canonical.href=location.href.split('#')[0];document.head.appendChild(canonical);
  root.innerHTML=`<article class="detail-card"><div class="detail-hero"><span class="date-badge">${event.date}</span><span class="place-badge">📍 ${event.city}</span><span class="emoji">${event.emoji}</span></div><div class="detail-content"><div class="verify-line"><span class="verified">✓ Quelle geprüft</span><span class="source-type">${event.source_type||'Geprüfte Quelle'}</span></div><div class="catline">${event.region} · ${event.cats.join(' · ')}</div><h1>${event.title}</h1><div class="detail-meta"><span>📅 ${event.date}</span><span>🕒 ${event.time}</span><span>📍 ${event.city}</span></div><p class="detail-desc">${event.desc}</p><div class="detail-actions"><a class="cta-btn" href="${event.source}" target="_blank" rel="noopener noreferrer">Offizielle Infos ↗</a><button class="cta-btn secondary" id="shareEvent">Teilen</button></div><p class="detail-note">Termine können sich kurzfristig ändern. Massgebend ist die verlinkte Originalquelle.</p></div></article>`;
  const jsonLd={"@context":"https://schema.org","@type":"Event","name":event.title,"startDate":event.start,"endDate":event.end,"description":event.desc,"eventStatus":"https://schema.org/EventScheduled","eventAttendanceMode":"https://schema.org/OfflineEventAttendanceMode","location":{"@type":"Place","name":event.city,"address":{"@type":"PostalAddress","addressLocality":event.city,"addressCountry":"CH"}},"url":location.href.split('#')[0],"sameAs":event.source};
  const script=document.createElement('script');script.type='application/ld+json';script.textContent=JSON.stringify(jsonLd);document.head.appendChild(script);
  document.getElementById('shareEvent').onclick=async()=>{const share={title:event.title,text:`${event.title} – ${event.date} in ${event.city}`,url:location.href};if(navigator.share){try{await navigator.share(share);}catch(e){}}else{await navigator.clipboard.writeText(location.href);alert('Link kopiert.');}};
}
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}