(()=>{
const DATA=window.EVENTS||[];
const NS='wasgehtheute-ch';
const favKey='wgh_favorites_v1';
const notifKey='wgh_weekend_notifications_v1';
let userPos=null,map=null,userMarker=null;
function slugify(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function eid(e){return slugify(e.title+'-'+e.city+'-'+e.start);}
function eventUrl(e){return new URL(`event.html?id=${encodeURIComponent(eid(e))}`,location.href).href;}
function getFavs(){try{return JSON.parse(localStorage.getItem(favKey)||'[]')}catch{return[]}}
function setFavs(v){localStorage.setItem(favKey,JSON.stringify(v));updateFavCount();}
function updateFavCount(){const el=document.getElementById('favoriteCount');if(el)el.textContent=getFavs().length;}
async function counter(name,up=false){try{const url=`https://api.counterapi.dev/v1/${NS}/${encodeURIComponent(name)}/${up?'up':''}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)return 0;const d=await r.json();return Number(d.count??d.value??0)||0}catch{return 0}}
function findEventFromCard(card){const title=card.querySelector('h3')?.textContent?.trim();const city=card.querySelector('.place-badge')?.textContent?.replace('📍','').trim();return DATA.find(e=>e.title===title&&e.city===city)||DATA.find(e=>e.title===title);}
function calendarText(e){const clean=x=>String(x||'').replace(/[\\;,]/g,m=>'\\'+m).replace(/\n/g,'\\n');const start=e.start.replaceAll('-','');const endDate=new Date(e.end+'T12:00:00');endDate.setDate(endDate.getDate()+1);const end=`${endDate.getFullYear()}${String(endDate.getMonth()+1).padStart(2,'0')}${String(endDate.getDate()).padStart(2,'0')}`;return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//WasGehtHeute.ch//DE\r\nBEGIN:VEVENT\r\nUID:${eid(e)}@wasgehtheute.ch\r\nDTSTART;VALUE=DATE:${start}\r\nDTEND;VALUE=DATE:${end}\r\nSUMMARY:${clean(e.title)}\r\nLOCATION:${clean(e.city)}\r\nDESCRIPTION:${clean(e.desc)}\\n${clean(e.source)}\r\nURL:${e.source}\r\nEND:VEVENT\r\nEND:VCALENDAR`;}
function downloadCalendar(e){const b=new Blob([calendarText(e)],{type:'text/calendar;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${slugify(e.title)}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);}
async function shareEvent(e){const payload={title:e.title,text:`${e.title} – ${e.date} in ${e.city}`,url:eventUrl(e)};if(navigator.share){try{await navigator.share(payload);return}catch{}}try{await navigator.clipboard.writeText(payload.url);alert('Link kopiert ✅')}catch{prompt('Link kopieren:',payload.url)}}
function decorateCards(){document.querySelectorAll('.card').forEach(card=>{if(card.dataset.enhanced)return;const e=findEventFromCard(card);if(!e)return;card.dataset.enhanced='1';const favs=getFavs();const id=eid(e);const body=card.querySelector('.card-body');const row=document.createElement('div');row.className='quick-actions';row.innerHTML=`<button class="quick-btn fav-btn" title="Favorit">${favs.includes(id)?'❤️':'🤍'}</button><button class="quick-btn share-btn" title="Teilen">📤</button><button class="quick-btn cal-btn" title="Kalender">📅</button>${e.ticket?'<a class="quick-btn ticket-btn" target="_blank" rel="noopener noreferrer">🎟️</a>':''}`;body.appendChild(row);row.querySelector('.fav-btn').onclick=()=>{let f=getFavs();if(f.includes(id))f=f.filter(x=>x!==id);else f.push(id);setFavs(f);row.querySelector('.fav-btn').textContent=f.includes(id)?'❤️':'🤍';};row.querySelector('.share-btn').onclick=()=>shareEvent(e);row.querySelector('.cal-btn').onclick=()=>downloadCalendar(e);if(e.ticket){const a=row.querySelector('.ticket-btn');a.href=e.ticket;a.onclick=()=>counter('ticket-'+id,true);}
card.querySelectorAll(`a[href*="event.html"]`).forEach(a=>a.addEventListener('click',()=>{counter('event-'+id,true);counter('city-'+slugify(e.city),true);(e.cats||[]).slice(0,2).forEach(c=>counter('cat-'+slugify(c),true));}));});}
const observer=new MutationObserver(()=>decorateCards());const grid=document.getElementById('grid');if(grid)observer.observe(grid,{childList:true});decorateCards();updateFavCount();

document.getElementById('favoritesBtn')?.addEventListener('click',()=>{const ids=getFavs();document.querySelectorAll('.card').forEach(c=>{const e=findEventFromCard(c);c.style.display=e&&ids.includes(eid(e))?'':'none';});const r=document.getElementById('result');if(r)r.textContent=`${ids.length} gespeicherte Favoriten`;});
function haversine(a,b){const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b[0]-a[0]),dLon=toRad(b[1]-a[1]);const q=Math.sin(dLat/2)**2+Math.cos(toRad(a[0]))*Math.cos(toRad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
function applyNear(){if(!userPos)return;const cards=[...document.querySelectorAll('.card')];cards.forEach(c=>{const e=findEventFromCard(c),p=e&&window.WGH_locationFor?.(e.city);c.dataset.distance=p?haversine(userPos,p).toFixed(2):'99999';let badge=c.querySelector('.distance-badge');if(!badge&&p){badge=document.createElement('span');badge.className='distance-badge';c.querySelector('.card-visual')?.appendChild(badge);}if(badge&&p)badge.textContent=`${Number(c.dataset.distance).toFixed(1)} km`;});cards.sort((a,b)=>Number(a.dataset.distance)-Number(b.dataset.distance)).forEach(c=>grid.appendChild(c));const r=document.getElementById('result');if(r)r.textContent='Nach Entfernung zu deinem Standort sortiert';}
function requestLocation(){if(!navigator.geolocation){alert('Standort wird von diesem Browser nicht unterstützt.');return;}navigator.geolocation.getCurrentPosition(pos=>{userPos=[pos.coords.latitude,pos.coords.longitude];applyNear();showUserOnMap();},()=>alert('Standort konnte nicht verwendet werden. Bitte Standortfreigabe erlauben.'),{enableHighAccuracy:false,timeout:10000,maximumAge:300000});}
document.getElementById('nearMeBtn')?.addEventListener('click',requestLocation);document.getElementById('mapNearMeBtn')?.addEventListener('click',requestLocation);

async function popularity(){const future=DATA.filter(e=>e.end>=(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zurich'}).format(new Date()))).slice(0,18);const scores=await Promise.all(future.map(async e=>({e,count:await counter('event-'+eid(e),false)})));scores.sort((a,b)=>b.count-a.count||a.e.start.localeCompare(b.e.start));const top=scores.filter(x=>x.count>0).slice(0,3);if(!top.length)return;const wrap=document.getElementById('topGrid');if(!wrap)return;wrap.innerHTML=top.map((x,i)=>`<article class="top-card"><div class="top-badge">${i===0?'🔥 Am beliebtesten':'⭐ Beliebt'} · ${x.count} Klick${x.count===1?'':'s'}</div><div class="top-emoji">${x.e.emoji}</div><div class="top-copy"><small>📍 ${x.e.city} · ${x.e.date}</small><h3><a href="${eventUrl(x.e)}">${x.e.title}</a></h3><p>${x.e.desc}</p><a class="top-link" href="${eventUrl(x.e)}">Event ansehen →</a></div></article>`).join('');document.getElementById('highlightText').textContent='Diese Events wurden von Besuchern am häufigsten geöffnet.';}
popularity();

function initMap(){const mapEl=document.getElementById('eventMap');if(!mapEl||!window.L)return;map=L.map(mapEl).setView([47.15,9.2],8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);const bounds=[];DATA.filter(e=>e.end>=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zurich'}).format(new Date())).forEach(e=>{const p=window.WGH_locationFor?.(e.city);if(!p)return;bounds.push(p);L.marker(p).addTo(map).bindPopup(`<b>${e.title}</b><br>${e.date}<br>${e.city}<br><a href="${eventUrl(e)}">Details</a>`);});if(bounds.length)map.fitBounds(bounds,{padding:[20,20],maxZoom:10});}
function showUserOnMap(){if(!map||!userPos)return;if(userMarker)userMarker.remove();userMarker=L.circleMarker(userPos,{radius:8}).addTo(map).bindPopup('Dein Standort').openPopup();map.setView(userPos,10);}
setTimeout(initMap,300);

async function setupNotification(){if(!('Notification' in window)){alert('Benachrichtigungen werden von diesem Browser nicht unterstützt.');return;}const permission=await Notification.requestPermission();if(permission==='granted'){localStorage.setItem(notifKey,'1');new Notification('WasGehtHeute.ch',{body:'Weekend-Erinnerung ist aktiviert. Solange du die App/Seite öffnest, zeigen wir dir passende Weekend-Events.'});document.getElementById('notifyBtn').textContent='🔔 Weekend-Erinnerung aktiv';}else alert('Benachrichtigungen wurden nicht erlaubt.');}
document.getElementById('notifyBtn')?.addEventListener('click',setupNotification);if(localStorage.getItem(notifKey)==='1'){const b=document.getElementById('notifyBtn');if(b)b.textContent='🔔 Weekend-Erinnerung aktiv';}

// Formular: ohne hinterlegte Empfängeradresse wird nichts vorgetäuscht.
const form=document.getElementById('actionForm');if(form){const old=form.cloneNode(true);form.replaceWith(old);old.addEventListener('submit',e=>{e.preventDefault();const status=document.getElementById('demoMsg');status.style.display='block';status.textContent='⚠️ Noch kein echter Empfänger verbunden. Sobald eine Kontakt-E-Mail oder ein Formular-Dienst eingerichtet ist, kann diese Anfrage direkt gesendet werden.';});}
})();