(()=>{
const DATA=window.EVENTS||[];
const CFG=window.WGH_CONFIG||{};
const NS=CFG.analyticsNamespace||'wasgehtheute-ch';
const favKey='wgh_favorites_v1',notifKey='wgh_weekend_notifications_v1';
let userPos=null,map=null,userMarker=null,mapLoaded=false;
const slugify=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ä/g,'ae').replace(/ö/g,'oe').replace(/ü/g,'ue').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const eid=e=>slugify(e.title+'-'+e.city+'-'+e.start);
const eventUrl=e=>new URL(`event.html?id=${encodeURIComponent(eid(e))}`,location.href).href;
function getFavs(){try{return JSON.parse(localStorage.getItem(favKey)||'[]')}catch{return[]}}
function setFavs(v){localStorage.setItem(favKey,JSON.stringify(v));updateFavCount()}
function updateFavCount(){const el=document.getElementById('favoriteCount');if(el)el.textContent=getFavs().length}
async function counter(name,up=false){try{const r=await fetch(`https://api.counterapi.dev/v1/${NS}/${encodeURIComponent(name)}/${up?'up':''}`,{cache:'no-store'});if(!r.ok)return 0;const d=await r.json();return Number(d.count??d.value??0)||0}catch{return 0}}
function findEventFromCard(card){const title=card.querySelector('h3')?.textContent?.trim(),city=card.querySelector('.place-badge')?.textContent?.replace('📍','').trim();return DATA.find(e=>e.title===title&&e.city===city)||DATA.find(e=>e.title===title)}
function eventPrice(e){if(e.price)return e.price;if((e.cats||[]).includes('Gratis'))return 'Gratis';return ''}
function eventVenue(e){return e.venue||e.location||e.city}
function calendarText(e){const clean=x=>String(x||'').replace(/[\\;,]/g,m=>'\\'+m).replace(/\n/g,'\\n');const start=e.start.replaceAll('-','');const endDate=new Date(e.end+'T12:00:00');endDate.setDate(endDate.getDate()+1);const end=`${endDate.getFullYear()}${String(endDate.getMonth()+1).padStart(2,'0')}${String(endDate.getDate()).padStart(2,'0')}`;return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//WasGehtHeute.ch//DE\r\nBEGIN:VEVENT\r\nUID:${eid(e)}@wasgehtheute.ch\r\nDTSTART;VALUE=DATE:${start}\r\nDTEND;VALUE=DATE:${end}\r\nSUMMARY:${clean(e.title)}\r\nLOCATION:${clean(eventVenue(e))}\r\nDESCRIPTION:${clean(e.desc)}\\n${clean(e.source)}\r\nURL:${e.source}\r\nEND:VEVENT\r\nEND:VCALENDAR`}
function downloadCalendar(e){const b=new Blob([calendarText(e)],{type:'text/calendar;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${slugify(e.title)}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
async function shareEvent(e){const payload={title:e.title,text:`${e.title} – ${e.date} in ${e.city}`,url:eventUrl(e)};if(navigator.share){try{await navigator.share(payload);return}catch{}}try{await navigator.clipboard.writeText(payload.url);alert('Link kopiert ✅')}catch{prompt('Link kopieren:',payload.url)}}
function decorateCards(){document.querySelectorAll('.card').forEach(card=>{if(card.dataset.enhanced)return;const e=findEventFromCard(card);if(!e)return;card.dataset.enhanced='1';const id=eid(e),body=card.querySelector('.card-body'),visual=card.querySelector('.card-visual');
 if(e.image&&visual){visual.style.backgroundImage=`linear-gradient(rgba(8,8,12,.22),rgba(8,8,12,.45)),url("${String(e.image).replace(/"/g,'')}")`;visual.style.backgroundSize='cover';visual.style.backgroundPosition='center';const em=visual.querySelector('.emoji');if(em)em.style.display='none'}
 const facts=document.createElement('div');facts.className='event-facts';const price=eventPrice(e),venue=eventVenue(e);facts.innerHTML=`${venue&&venue!==e.city?`<span>📍 ${venue}</span>`:''}${price?`<span>💳 ${price}</span>`:''}`;if(facts.children.length)body.insertBefore(facts,body.querySelector('.card-foot'));
 const row=document.createElement('div');row.className='quick-actions';row.innerHTML=`<button class="quick-btn fav-btn" aria-label="Favorit speichern">${getFavs().includes(id)?'❤️':'🤍'}</button><button class="quick-btn share-btn" aria-label="Event teilen">📤</button><button class="quick-btn cal-btn" aria-label="Zum Kalender hinzufügen">📅</button>${e.ticket?'<a class="quick-btn ticket-btn" target="_blank" rel="noopener noreferrer" aria-label="Tickets">🎟️</a>':''}`;body.appendChild(row);
 row.querySelector('.fav-btn').onclick=()=>{let f=getFavs();f=f.includes(id)?f.filter(x=>x!==id):[...f,id];setFavs(f);row.querySelector('.fav-btn').textContent=f.includes(id)?'❤️':'🤍'};row.querySelector('.share-btn').onclick=()=>shareEvent(e);row.querySelector('.cal-btn').onclick=()=>downloadCalendar(e);if(e.ticket){const a=row.querySelector('.ticket-btn');a.href=e.ticket;a.onclick=()=>counter('ticket-'+id,true)}
 card.querySelectorAll(`a[href*="event.html"]`).forEach(a=>a.addEventListener('click',()=>{counter('event-'+id,true);counter('city-'+slugify(e.city),true);(e.cats||[]).slice(0,2).forEach(c=>counter('cat-'+slugify(c),true))}))})}
const grid=document.getElementById('grid');if(grid)new MutationObserver(()=>requestAnimationFrame(decorateCards)).observe(grid,{childList:true});decorateCards();updateFavCount();
document.getElementById('favoritesBtn')?.addEventListener('click',()=>{const ids=getFavs();document.querySelectorAll('.card').forEach(c=>{const e=findEventFromCard(c);c.style.display=e&&ids.includes(eid(e))?'':'none'});const r=document.getElementById('result');if(r)r.textContent=`${ids.length} gespeicherte Favoriten`});
function haversine(a,b){const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b[0]-a[0]),dLon=toRad(b[1]-a[1]),q=Math.sin(dLat/2)**2+Math.cos(toRad(a[0]))*Math.cos(toRad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function applyNear(){if(!userPos)return;const cards=[...document.querySelectorAll('.card')];cards.forEach(c=>{const e=findEventFromCard(c),p=e&&window.WGH_locationFor?.(e.city);c.dataset.distance=p?haversine(userPos,p).toFixed(2):'99999';let badge=c.querySelector('.distance-badge');if(!badge&&p){badge=document.createElement('span');badge.className='distance-badge';c.querySelector('.card-visual')?.appendChild(badge)}if(badge&&p)badge.textContent=`${Number(c.dataset.distance).toFixed(1)} km`});cards.sort((a,b)=>Number(a.dataset.distance)-Number(b.dataset.distance)).forEach(c=>grid.appendChild(c));const r=document.getElementById('result');if(r)r.textContent='Nach Entfernung zu deinem Standort sortiert'}
function requestLocation(){if(!navigator.geolocation){alert('Standort wird von diesem Browser nicht unterstützt.');return}navigator.geolocation.getCurrentPosition(pos=>{userPos=[pos.coords.latitude,pos.coords.longitude];applyNear();showUserOnMap()},()=>alert('Standort konnte nicht verwendet werden. Bitte Standortfreigabe erlauben.'),{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}
document.getElementById('nearMeBtn')?.addEventListener('click',requestLocation);document.getElementById('mapNearMeBtn')?.addEventListener('click',()=>{loadMap().then(requestLocation)});
async function popularity(){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zurich'}).format(new Date()),future=DATA.filter(e=>e.end>=today).slice(0,matchMedia('(max-width:820px)').matches?6:18),scores=[];for(const e of future)scores.push({e,count:await counter('event-'+eid(e),false)});scores.sort((a,b)=>b.count-a.count||a.e.start.localeCompare(b.e.start));const top=scores.filter(x=>x.count>0).slice(0,3),wrap=document.getElementById('topGrid');if(!top.length||!wrap)return;wrap.innerHTML=top.map((x,i)=>`<article class="top-card"><div class="top-badge">${i===0?'🔥 Am beliebtesten':'⭐ Beliebt'} · ${x.count} Klick${x.count===1?'':'s'}</div><div class="top-emoji">${x.e.emoji}</div><div class="top-copy"><small>📍 ${x.e.city} · ${x.e.date}</small><h3><a href="${eventUrl(x.e)}">${x.e.title}</a></h3><p>${x.e.desc}</p><a class="top-link" href="${eventUrl(x.e)}">Event ansehen →</a></div></article>`).join('');document.getElementById('highlightText').textContent='Diese Events wurden von Besuchern am häufigsten geöffnet.'}
if('requestIdleCallback' in window)requestIdleCallback(()=>popularity(),{timeout:2500});else setTimeout(popularity,1200);
function injectCss(href){return new Promise((res,rej)=>{if(document.querySelector(`link[href="${href}"]`))return res();const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.onload=res;l.onerror=rej;document.head.appendChild(l)})}
function injectScript(src){return new Promise((res,rej)=>{if(window.L)return res();const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.body.appendChild(s)})}
async function loadMap(){if(mapLoaded)return;const btn=document.getElementById('loadMapBtn');if(btn){btn.disabled=true;btn.textContent='Karte lädt…'}try{await Promise.all([injectCss('https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'),injectScript('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js')]);initMap();mapLoaded=true;if(btn){btn.textContent='✓ Karte geladen';btn.disabled=true}}catch{if(btn){btn.textContent='Karte erneut laden';btn.disabled=false}alert('Karte konnte gerade nicht geladen werden.')}}
document.getElementById('loadMapBtn')?.addEventListener('click',loadMap);document.querySelector('a[href="#mapSection"]')?.addEventListener('click',()=>setTimeout(loadMap,250));
function initMap(){const mapEl=document.getElementById('eventMap');if(!mapEl||!window.L||map)return;map=L.map(mapEl,{scrollWheelZoom:false}).setView([47.15,9.2],8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zurich'}).format(new Date()),bounds=[];DATA.filter(e=>e.end>=today).forEach(e=>{const p=window.WGH_locationFor?.(e.city);if(!p)return;bounds.push(p);L.marker(p).addTo(map).bindPopup(`<b>${e.title}</b><br>${e.date}<br>${eventVenue(e)}<br><a href="${eventUrl(e)}">Details</a>`)});if(bounds.length)map.fitBounds(bounds,{padding:[20,20],maxZoom:10});setTimeout(()=>map.invalidateSize(),100);if(userPos)showUserOnMap()}
function showUserOnMap(){if(!map||!userPos)return;if(userMarker)userMarker.remove();userMarker=L.circleMarker(userPos,{radius:8}).addTo(map).bindPopup('Dein Standort').openPopup();map.setView(userPos,10)}
async function setupNotification(){if(CFG.pushSubscribeEndpoint){alert('Push-Backend ist konfiguriert. Die Server-Anmeldung wird beim nächsten Backend-Schritt aktiviert.');return}if(!('Notification' in window)){alert('Benachrichtigungen werden von diesem Browser nicht unterstützt.');return}const permission=await Notification.requestPermission();if(permission==='granted'){localStorage.setItem(notifKey,'1');new Notification('WasGehtHeute.ch',{body:'Lokale Weekend-Erinnerung ist aktiviert. Für echte automatische Push-Nachrichten braucht die Website noch einen Push-Server.'});const b=document.getElementById('notifyBtn');if(b)b.textContent='🔔 Erinnerung aktiv'}else alert('Benachrichtigungen wurden nicht erlaubt.')}
document.getElementById('notifyBtn')?.addEventListener('click',setupNotification);if(localStorage.getItem(notifKey)==='1'){const b=document.getElementById('notifyBtn');if(b)b.textContent='🔔 Erinnerung aktiv'}
async function submitRequest(form){const status=document.getElementById('demoMsg'),payload={name:document.getElementById('formName').value,email:document.getElementById('formEmail').value,type:document.getElementById('requestType').value,subject:document.getElementById('formSubject').value,place:document.getElementById('formPlace').value,date:document.getElementById('formDate').value,link:document.getElementById('formLink').value,message:document.getElementById('formMessage').value,page:location.href,createdAt:new Date().toISOString()};status.style.display='block';if(CFG.formEndpoint){status.textContent='Wird gesendet…';try{const r=await fetch(CFG.formEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error();status.textContent='✅ Anfrage wurde gesendet.';form.reset()}catch{status.textContent='⚠️ Versand fehlgeschlagen. Bitte später erneut versuchen.'}return}if(CFG.contactEmail){const subject=encodeURIComponent(`[WasGehtHeute] ${payload.type}: ${payload.subject}`),body=encodeURIComponent(`${payload.name}\n${payload.email}\n${payload.place}\n${payload.date}\n${payload.link}\n\n${payload.message}`);location.href=`mailto:${CFG.contactEmail}?subject=${subject}&body=${body}`;status.textContent='E-Mail-Programm wurde geöffnet.';return}status.textContent='⚠️ Noch kein Empfänger oder Formular-Backend hinterlegt. Deine Angaben wurden nicht versendet.'}
const form=document.getElementById('actionForm');if(form){const clone=form.cloneNode(true);form.replaceWith(clone);clone.addEventListener('submit',e=>{e.preventDefault();submitRequest(clone)})}
})();