(()=>{
const K='wgh_organizer_drafts_v1',CFG=window.WGH_CONFIG||{},form=document.getElementById('orgForm'),msg=document.getElementById('orgMsg'),list=document.getElementById('orgDrafts');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){try{const v=JSON.parse(localStorage.getItem(K)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function write(v){try{localStorage.setItem(K,JSON.stringify(v))}catch{}}
function draw(){if(!list)return;const rows=read();list.innerHTML=rows.length?rows.map((x,i)=>`<div class="rank-row"><div><b>${esc(x.title||'Ohne Titel')}</b><br><small>${esc(x.date||'Kein Datum')} · ${esc(x.place||'Kein Ort')}${x.venue?' · '+esc(x.venue):''} · ${esc(x.org||'Unbekannt')}<br>Status: ${esc(x.status||'lokale Kopie')}</small></div><button type="button" class="quick-btn" data-remove-draft="${i}" aria-label="Gespeicherte Kopie löschen">🗑️</button></div>`).join(''):'<p>Noch keine gespeicherten Einreichungen auf diesem Gerät.</p>'}
list?.addEventListener('click',e=>{const b=e.target.closest('[data-remove-draft]');if(!b)return;const rows=read();rows.splice(Number(b.dataset.removeDraft),1);write(rows);draw()});
function val(id){return document.getElementById(id)?.value?.trim?.()||''}
form?.addEventListener('submit',async e=>{e.preventDefault();const item={org:val('orgName'),email:val('orgEmail'),title:val('orgTitle'),date:val('orgDate'),time:val('orgTime'),place:val('orgPlace'),venue:val('orgVenue'),category:val('orgCategory'),desc:val('orgDesc'),website:val('orgWebsite'),ticket:val('orgTicket'),price:val('orgPrice'),image:val('orgImage'),imageRights:val('orgImageRights'),created:new Date().toISOString(),type:'Veranstalter-Einreichung',status:'Wird vorbereitet',page:location.href};const rows=read();rows.unshift(item);write(rows);draw();if(!CFG.organizerEndpoint){item.status='Nur lokal gespeichert · noch nicht online eingereicht';write(rows);draw();if(msg)msg.textContent='⚠️ Online-Versand ist momentan noch nicht verbunden. Deine Eingabe wurde nur auf diesem Gerät gespeichert und nicht veröffentlicht.';return}if(msg)msg.textContent='Wird sicher zur Prüfung gesendet…';item.status='Wird gesendet';write(rows);draw();try{const r=await fetch(CFG.organizerEndpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(item)});if(!r.ok)throw new Error();item.status='Wartet auf Prüfung';item.submittedAt=new Date().toISOString();write(rows);draw();if(msg)msg.textContent='✅ Einreichung empfangen. Status: Wartet auf Prüfung. Der Event wird nicht automatisch veröffentlicht.';form.reset()}catch{item.status='Versand fehlgeschlagen · nur lokal gespeichert';write(rows);draw();if(msg)msg.textContent='⚠️ Versand fehlgeschlagen. Die lokale Kopie bleibt gespeichert; öffentlich wurde nichts veröffentlicht.'}});
draw();
})();
