(()=>{
const DATA=Array.isArray(window.EVENTS)?window.EVENTS:[];
const U=window.WGH_EVENT_UTILS||{};
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Zurich'}).format(new Date());
const q=document.getElementById('q'),area=document.getElementById('area'),place=document.getElementById('place');
const ymd=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function weekend(){const d=new Date(today+'T12:00:00'),dow=d.getDay();let add=(5-dow+7)%7;if(dow===6)add=-1;if(dow===0)add=-2;const f=new Date(d);f.setDate(d.getDate()+add);const s=new Date(f);s.setDate(f.getDate()+2);return[ymd(f),ymd(s)]}
function safe(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function eventId(e){return window.WGH_APP?.eventId?.(e)||U.id?.(e)||''}
function eventUrl(e){return window.WGH_APP?.eventUrl?.(e)||`event.html?id=${encodeURIComponent(eventId(e))}`}
function isPublic(e){return e&&e.end>=today&&e.quality_status!=='cancelled-warning'&&e.status!=='cancelled'}
function baseFiltered(){const term=q?.value?.trim()||'',av=area?.value||'',pv=place?.value||'';return DATA.filter(e=>isPublic(e)&&(!av||e.region===av)&&(!pv||e.city===pv)&&(!term||(U.fuzzyMatch?U.fuzzyMatch(e,term):String([e.title,e.city,e.venue,(e.cats||[]).join(' ')].join(' ')).toLowerCase().includes(term.toLowerCase()))))}
function timeHour(e){const m=String(e.time||'').match(/(?:^|\D)([01]?\d|2[0-3])[:.]/);return m?Number(m[1]):null}
function smallCard(e){const p=e.price||(e.cats||[]).includes('Gratis')?'Gratis':e.price||'';const status=e.status_label&&e.status!=='confirmed'?`<span>${safe(e.status_label)}</span>`:'';return `<article class="smart-event-card"><small>📍 ${safe(e.city)}${e.venue?' · '+safe(e.venue):''}</small><b>${safe(e.title)}</b><div class="smart-event-meta"><span>🕒 ${safe(e.time||'Zeit siehe Quelle')}</span>${p?`<span>💳 ${safe(p)}</span>`:''}${status}</div><a href="${safe(eventUrl(e))}">Details →</a></article>`}
function smartBlock(title,sub,items,id){return `<section class="smart-block"><div class="smart-block-head"><div><h2>${title}</h2><p>${sub}</p></div><button type="button" data-smart-jump="${id}">Alle anzeigen</button></div><div class="smart-event-row" id="${id}">${items.length?items.slice(0,8).map(smallCard).join(''):'<div class="smart-empty">Aktuell keine passenden Events in diesem Zeitraum.</div>'}</div></section>`}
let discovery=document.getElementById('smartDiscovery');
if(!discovery){discovery=document.createElement('section');discovery.id='smartDiscovery';discovery.className='smart-discovery';const anchor=document.getElementById('mobileFilters')||document.querySelector('.highlights-section');anchor?.insertAdjacentElement('afterend',discovery)}
function renderSmart(){if(!discovery)return;const base=baseFiltered(),[fri,sun]=weekend();const todayItems=base.filter(e=>e.start<=today&&e.end>=today).sort((a,b)=>String(a.time||'99:99').localeCompare(String(b.time||'99:99')));const evening=todayItems.filter(e=>{const h=timeHour(e);return h!==null?h>=17:(e.cats||[]).some(c=>['Party','Club','Bar','Musik','Festival'].includes(c))});const we=base.filter(e=>e.start<=sun&&e.end>=fri).sort((a,b)=>String(a.start).localeCompare(String(b.start))||String(a.time||'').localeCompare(String(b.time||'')));discovery.innerHTML=smartBlock('🔥 Heute in deiner Region',`${todayItems.length} passende Events heute`,todayItems,'smartToday')+smartBlock('🌙 Heute Abend',`${evening.length} Events für den Abend`,evening,'smartEvening')+smartBlock('🎉 Dieses Wochenende',`${we.length} Events von Freitag bis Sonntag`,we,'smartWeekend')}
['input','change'].forEach(type=>{q?.addEventListener(type,()=>requestAnimationFrame(renderSmart));area?.addEventListener(type,()=>requestAnimationFrame(renderSmart));place?.addEventListener(type,()=>requestAnimationFrame(renderSmart))});
document.addEventListener('click',e=>{const b=e.target.closest('[data-smart-jump]');if(!b)return;document.getElementById(b.dataset.smartJump)?.scrollIntoView({behavior:'smooth',block:'center'})});
function decorateCards(){document.querySelectorAll('.card[data-event-id]').forEach(card=>{const e=DATA.find(x=>eventId(x)===card.dataset.eventId);if(!e)return;const verified=card.querySelector('.verified');const checked=U.checkedAt?.(e)||e.checked_at||e.health_checked_at||e.verified_at||'';if(verified){verified.dataset.fresh='1';verified.textContent=checked?`✓ Quelle geprüft · ${checked.split('-').reverse().join('.')}`:'✓ Quelle geprüft'}if(e.status&&e.status!=='confirmed'&&!card.querySelector('.status-badge')){const badge=document.createElement('span');badge.className=`status-badge ${e.status}`;badge.textContent=e.status_label||e.status;card.querySelector('.verify-line')?.appendChild(badge)}})}
window.addEventListener('wgh:render',()=>{requestAnimationFrame(()=>{decorateCards();renderSmart();applyRadiusVisibility()})});
const trust=document.createElement('div');trust.className='trust-note';trust.innerHTML='<b>✓ Geprüfte Originalquellen</b><br>WasGehtHeute übernimmt Termine aus offiziellen und geprüften Quellen. Veranstaltungen können sich trotzdem kurzfristig ändern. Bitte prüfe bei wichtigen Veranstaltungen zusätzlich die verlinkte Originalquelle.';const fi=document.querySelector('.footer-info');if(fi&&!document.querySelector('.trust-note'))fi.insertAdjacentElement('afterend',trust);
let userPos=null,radius=25,distances={};
const promo=document.querySelector('.nearby-promo-copy');
if(promo&&!document.getElementById('radiusSelect')){const controls=document.createElement('div');controls.className='nearby-controls';controls.innerHTML='<label>Radius <select id="radiusSelect" aria-label="Radius für Events in der Nähe"><option value="10">10 km</option><option value="25" selected>25 km</option><option value="50">50 km</option><option value="80">80 km</option><option value="120">120 km</option></select></label><span class="nearby-result" id="nearbyResult">Standort noch nicht aktiviert</span>';promo.appendChild(controls);document.getElementById('radiusSelect')?.addEventListener('change',e=>{radius=Number(e.target.value)||25;if(userPos)applyNear()})}
function haversine(a,b){const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b[0]-a[0]),dLon=toRad(b[1]-a[1]),x=Math.sin(dLat/2)**2+Math.cos(toRad(a[0]))*Math.cos(toRad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function applyRadiusVisibility(){if(!userPos)return;let shown=0;document.querySelectorAll('#grid .card[data-event-id]').forEach(card=>{const d=distances[card.dataset.eventId];const ok=Number.isFinite(d)&&d<=radius;card.style.display=ok?'':'none';if(ok)shown++});const result=document.getElementById('nearbyResult');if(result)result.textContent=`${shown} sichtbare Events im Umkreis von ${radius} km`;const mainResult=document.getElementById('result');if(mainResult)mainResult.textContent=`${shown} Events im Umkreis von ${radius} km`}
function applyNear(){if(!userPos)return;distances={};DATA.filter(isPublic).forEach(e=>{const p=window.WGH_locationFor?.(e.city);if(p)distances[eventId(e)]=haversine(userPos,p)});window.WGH_APP?.setDistances?.(distances);requestAnimationFrame(applyRadiusVisibility)}
function requestLocation(){if(!navigator.geolocation){alert('Standort wird von diesem Browser nicht unterstützt.');return}const r=document.getElementById('nearbyResult');if(r)r.textContent='Standort wird ermittelt…';navigator.geolocation.getCurrentPosition(pos=>{userPos=[pos.coords.latitude,pos.coords.longitude];applyNear()},()=>{if(r)r.textContent='Standortfreigabe nicht erlaubt';alert('Standort konnte nicht verwendet werden. Bitte Standortfreigabe erlauben.')},{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}
document.addEventListener('click',e=>{if(!e.target.closest('#nearMeBtn,#nearbyPromoBtn'))return;e.preventDefault();e.stopImmediatePropagation();requestLocation()},true);
window.addEventListener('wgh:more-events',()=>requestAnimationFrame(applyRadiusVisibility));
renderSmart();decorateCards();
})();
