window.WGH_CONFIG={
  contactEmail:"",
  formEndpoint:"",
  organizerEndpoint:"",
  pushSubscribeEndpoint:"",
  authEndpoint:"supabase-auth",
  customDomain:"",
  analyticsNamespace:"wasgehtheute.ch",
  adminMode:"supabase-auth",
  supabaseRequests:true
};
