window.WGH_CONFIG={
  contactEmail:"",
  formEndpoint:"https://formspree.io/f/xkjwkyyz",
  organizerEndpoint:"https://formspree.io/f/xkjwkyyz",
  pushSubscribeEndpoint:"",
  authEndpoint:"",
  customDomain:"",
  analyticsNamespace:"wasgehtheute.ch",
  adminMode:"static-preview"
};
